name: 'lsa_dbt'
version: '1.0.0'

profile: 'lsa_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]

# Include other folder paths containing HMIS CSVs 
seed-paths: [
  "seeds",
  "../Sample Data/Sample HMIS Data",
]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Define DBT vars
vars:
  lsa_config:
    report_dates:
      start: '2020-01-01'
      end: '2020-12-31'
    report_coc: 'XX-501'
    software_vendor: 'Sample Code Inc.'
    software_name: 'LSA Online'
    vendor_contact: 'Molly'
    vendor_email: 'cthomasbrittain@nowhere.com'

    # Define the LSA scope
    lsa_scope: 1
